safe:    true
lsi:     false
baseurl: /
url:     http://pichak.co

source:      .
destination: ./_site
plugins:     ./_plugins

future:   true

exclude: [vendor,Makefile, Gemfile, Gemfile.lock, LICENSE,"pichak.sublime-project","pichak.sublime-workspace","bootstrap-sass"]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "web"
      author: "Morteza Milani"

navigation:
- title: About
  url:   /
  alt: "About Pichak Co."
- title: Products
  url:   '/#products'
  alt: "See our products"
- title: Team
  url: /team
  alt: ""
- title: Jobs
  url: /jobs
  alt: ""
- title: Contact
  url: mailto:hello@pichak.co
  alt: ""

people:
- title: Hasan Aghdasi
- title: Alireza Arabi
- title: Vahid Ashrafian
- title: Faezeh Attarzadeh
- title: Mojtaba Azad
- title: Arash Badie Modiri
- title: Ali Ehsanfar
- title: Sepideh Gheysar
- title: Mojtaba Khodabandeh
- title: Kimia Maleki
- title: Morteza Milani
- title: Amir Nourian
- title: Ali Pourhadi
- title: Mohammad M. Ramezanpour
- title: Hamid Rezazadeh
- title: Sadegh Saati
- title: Shadi Sabzali
- title: Amir Sabbaghi

gems:
- bootstrap-sass
