safe:    true
lsi:     false
baseurl: /
url:     http://pichak.co

source:      .
destination: ./_site
plugins:     ./_plugins

future:   true

exclude: [vendor,Makefile, Gemfile, Gemfile.lock, LICENSE,"pichak.sublime-project","pichak.sublime-workspace","bootstrap-sass"]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "web"
      author: "Morteza Milani"

navigation:
- title: About
  url:   /
  alt: "About Pichak Co."
- title: Products
  url:   '/#products'
  alt: "See our products"
- title: Team
  url: /team
  alt: ""
- title: Jobs
  url: /jobs
  alt: ""
- title: Contact
  url: mailto:hello@pichak.co
  alt: ""

people:
- title: Hasan Aghdasi
- title: Alireza Borzabadi
- title: Vahid Ashrafian
- title: Faezeh Attarzadeh
- title: Ali Ehsanfar
- title: Sepideh Gheysar
- title: Mojtaba Khodabandeh
- title: Kimia Maleki
- title: Morteza Milani
- title: Hamid Rezazadeh
- title: Shadi Sabzali
- title: Amir Sabbaghi
- title: Mohsen Damoukh
- title: Mahdi Dibaiee
- title: Zahra Esmaelipour
- title: Ali Fattaholmanan
- title: Mohamad Gheysariha
- title: Shayan Hashemi
- title: Alireza Maddahi
- title: Behnam Pishali
- title: Fahime Ghasemi
- title: Sama Ghoba
#- title: Farzaneh Gholipour
- title: Ehsan Rahimi
- title: Iman Rahmatizadeh
- title: Iman Roomana
- title: Hasan Tabatabaie

gems:
- bootstrap-sass
